export default [
  {
    title: 'Dashboard',
    icon: { icon: 'tabler-layout-dashboard' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Learn',
    icon: { icon: 'tabler-bulb' },
    to: 'learn',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'My Portfolio',
    icon: { icon: 'tabler-user' },
    to: 'portfolio',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Workbook',
    icon: { icon: 'tabler-book' },
    to: 'workbook',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'The Seed E-book',
    icon: { icon: 'tabler-books' },
    to: 'seed',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Claim Assistance',
    icon: { icon: 'tabler-credit-card' },
    to: 'claims',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Other Benefits',
    icon: { icon: 'tabler-circle-check' },
    to: 'benefits',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'My Earnings',
    icon: { icon: 'tabler-cash' },
    to: 'earnings',
    action: 'manage',
    subject: 'member',
  },
]
