export default [
  {
    title: 'Dashboard',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Learn',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'My Portfolio',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Workbook',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'The Seed E-book',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Claim Assistance',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'Other Benefits',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'member',
  },
  {
    title: 'My Earnings',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'manage',
    subject: 'admin',
  },
]
